apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-mn-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres_mn_db
  template:
    metadata:
      labels:
        app: postgres_mn_db
    spec:
      containers:
      - name: postgres
        image: postgres:17
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "diego"
        - name: POSTGRES_PASSWORD
          value: "diego"
        - name: POSTGRES_DB
          value: "manager_person"