apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: dev
spec:
  rules:
    - host: java-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: java-app
                port:
                  number: 8079
    - host: go-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-app
                port:
                  number: 8787
    - host: challenge-english.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: challenge-english
                port:
                  number: 8097
